apiVersion: v1
kind: Namespace
metadata:
  name: kctl-build
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build
  namespace: kctl-build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kctl-builder:view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: build
  namespace: kctl-build
---
apiVersion: v1
kind: Pod
metadata:
  namespace: kctl-build
  labels:
    run: test-kubectl
  name: test-kubectl
spec:
  serviceAccountName: build
  containers:
  - image: trmatthe/kubectl:1
    name: test-kubectl
  restartPolicy: Never

